import { useState } from 'react';
import { Server, Activity, Database, GitCompare, Code2, Terminal, Key, Zap } from 'lucide-react';

const ENDPOINTS = [
  {
    id: 'solve-sync',
    method: 'POST',
    path: '/api/solve-sync',
    title: 'Synchronous Pipeline Execution',
    icon: Zap,
    description: 'A unified, all-in-one endpoint that configures the scenario, runs the hybrid quantum-classical pipeline, and returns the finalized routing assignments in a single blocking request. Ideal for simpler integrations and smaller problem instances. For long-running large instances, use the decoupled asynchronous endpoints below.',
    payload: {
      depot: { id: 0, name: "Central Hub", lat: 13.0827, lon: 80.2707 },
      clinics: [
        { id: 1, name: "Node Alpha", lat: 13.0900, lon: 80.2800, demand: { f: 2, c: 5, a: 10 } }
      ],
      vehicles: [
        {
          id: "V1",
          compartments: { f: { temp_c: -20, capacity: 15 }, c: { temp_c: 4, capacity: 15 }, a: { temp_c: 20, capacity: 15 } }
        }
      ]
    },
    // yet to be added
    response: { 
      solver: "Hybrid QAOA Pipeline",
      status: "ok",
      fleet_distance: 42.5,
      fleet_spoilage: 120.0,
      fleet_total_cost: 162.5,
      routes: {
        "V1": {
          route: [0, 1, 0],
          distance_km: 42.5,
          spoilage_rs: 120.0,
          feasible: true,
          capacity: { f: { used: 2, cap: 15 }, c: { used: 5, cap: 15 }, a: { used: 10, cap: 15 } }
        }
      }
    }
  },
  {
    id: 'configure',
    method: 'POST',
    path: '/api/configure',
    title: 'Configure Routing Scenario',
    icon: Database,
    description: 'Initializes the dynamic routing scenario. Defines the geographical nodes (depot, drop-off locations), available vehicle fleet, and the multi-compartment demands for each node. Goods are categorized abstractly by temperature constraints: frozen (f), chilled (c), and ambient (a).',
    payload: {
      depot: { id: 0, name: "Central Hub", lat: 13.0827, lon: 80.2707 },
      clinics: [
        { id: 1, name: "Node Alpha", lat: 13.0900, lon: 80.2800, demand: { f: 2, c: 5, a: 10 } },
        { id: 2, name: "Node Beta", lat: 13.1000, lon: 80.2500, demand: { f: 0, c: 2, a: 4 } }
      ],
      vehicles: [
        {
          id: "V1",
          compartments: {
            f: { temp_c: -20, capacity: 15 },
            c: { temp_c: 4, capacity: 15 },
            a: { temp_c: 20, capacity: 15 }
          }
        }
      ]
    },
    response: { status: "success", message: "Dynamic scenario configured successfully." }
  },
  {
    id: 'run',
    method: 'GET',
    path: '/api/run-pipeline',
    title: 'Execute Hybrid QAOA (SSE)',
    icon: Activity,
    description: 'Triggers the execution of the full hybrid quantum-classical pipeline. Returns a Server-Sent Events (SSE) stream containing real-time execution logs, quantum sub-cluster partitioning details, QAOA optimizer iterations, and classical stitcher consensus.',
    notes: 'Clients should connect using an EventSource to receive the text/event-stream in real-time. The connection remains open until the pipeline completes.'
  },
  {
    id: 'results',
    method: 'GET',
    path: '/api/results',
    title: 'Fetch Final Optimized Routes',
    icon: Server,
    description: 'Retrieves the finalized, post-optimized routing assignments generated by the Hybrid QAOA pipeline. Contains the complete node sequence for each vehicle, geographic coordinates, capacity utilizations, and calculated objective costs.',
    response: {
      solver: "Hybrid QAOA Pipeline",
      status: "ok",
      fleet_distance: 42.5,
      fleet_spoilage: 120.0,
      fleet_total_cost: 162.5,
      routes: {
        "V1": {
          route: [0, 2, 1, 0],
          distance_km: 42.5,
          spoilage_rs: 120.0,
          feasible: true,
          capacity: {
            f: { used: 2, cap: 15 },
            c: { used: 7, cap: 15 },
            a: { used: 14, cap: 15 }
          },
          stops: [
            { id: 0, name: "Central Hub", lat: 13.0827, lon: 80.2707 },
            { id: 2, name: "Node Beta", lat: 13.1000, lon: 80.2500 },
            { id: 1, name: "Node Alpha", lat: 13.0900, lon: 80.2800 },
            { id: 0, name: "Central Hub", lat: 13.0827, lon: 80.2707 }
          ]
        }
      }
    }
  },
  {
    id: 'compare',
    method: 'GET',
    path: '/api/compare-results',
    title: 'Fetch Solver Benchmarks',
    icon: GitCompare,
    description: 'Retrieves benchmark comparison data across all configured scenarios. Instantly returns cached Classical, OR-Tools, ALNS, and ILP (PuLP/Gurobi) solver results. If data is missing or stale, it seamlessly triggers background evaluation and returns partial data.',
    response: {
      easy: {
        classical: { status: "ok", fleet_total_cost: 210.0 },
        ortools: { status: "ok", fleet_total_cost: 195.5 },
        pulp_cbc: { status: "ok", fleet_total_cost: 195.5 },
        qaoa: { status: "ok", fleet_total_cost: 192.0 }
      }
    }
  }
];

export default function ExplainerTab({ activeTab }) {
  const [selectedEndpoint, setSelectedEndpoint] = useState('solve-sync');

  if (activeTab !== 'explainer') return null;

  const currentEP = ENDPOINTS.find(ep => ep.id === selectedEndpoint);

  return (
    <div className="input-layout" style={{ height: '100%' }}>
      {/* ─── LEFT PANEL ─────────────────────────────────────────── */}
      <div className="input-left">
        <div className="input-sections">
          
          {/* Section A — API Endpoints */}
          <section className="input-section">
            <div className="input-section-header">
              <div>
                <div className="input-section-title">API Reference</div>
                <div className="input-section-sub">Integrate the Hybrid QAOA solver into your own logistics stack.</div>
              </div>
            </div>

            <div className="clinic-list-scroll" style={{ maxHeight: 'none', display: 'flex', flexDirection: 'column', gap: '8px' }}>
              {ENDPOINTS.map((ep) => {
                const isSelected = selectedEndpoint === ep.id;
                const Icon = ep.icon;
                return (
                  <div 
                    key={ep.id}
                    className={`api-endpoint-row ${isSelected ? 'active' : ''}`}
                    onClick={() => setSelectedEndpoint(ep.id)}
                    style={{
                      background: isSelected ? '#fff' : '#111',
                      border: `1px solid ${isSelected ? '#fff' : '#333'}`,
                      borderRadius: '8px',
                      padding: '12px 16px',
                      cursor: 'pointer',
                      display: 'flex',
                      alignItems: 'center',
                      gap: '12px',
                      transition: 'all 0.2s'
                    }}
                  >
                    <div style={{ color: isSelected ? '#000' : '#888' }}>
                      <Icon size={18} />
                    </div>
                    <div style={{ flex: 1, display: 'flex', flexDirection: 'column', gap: '2px' }}>
                      <span style={{ color: isSelected ? '#000' : '#fff', fontWeight: 'bold', fontSize: '14px' }}>
                        {ep.title}
                      </span>
                      <span style={{ color: isSelected ? '#555' : '#888', fontSize: '12px', fontFamily: 'var(--font-mono)', display: 'flex', alignItems: 'center' }}>
                        <span style={{ 
                          fontWeight: 'bold', 
                          marginRight: '8px',
                          background: isSelected ? '#000' : 'transparent',
                          color: isSelected ? '#fff' : '#888',
                          border: isSelected ? 'none' : '1px solid #444',
                          padding: '2px 6px',
                          borderRadius: '4px',
                          fontSize: '11px'
                        }}>{ep.method}</span>
                        {ep.path}
                      </span>
                    </div>
                  </div>
                );
              })}
            </div>
          </section>

          {/* Section B — Auth */}
          <section className="input-section">
            <div className="input-section-header">
              <div>
                <div className="input-section-title">Authentication</div>
                <div className="input-section-sub">
                  This local API is unauthenticated by default. For execution on IBM Quantum Hardware, ensure <span style={{ color: '#fff', background: '#000', padding: '2px 4px', borderRadius: '4px', border: '1px solid #444', fontFamily: 'var(--font-mono)' }}>IBM_QUANTUM_TOKEN</span> is set in the backend environment variables.
                </div>
              </div>
            </div>
          </section>

        </div>
      </div>

      {/* ─── RIGHT PANEL ─────────────────────────────────────────── */}
      <div className="input-right">
        <div className="map-shell input-map-shell" style={{ display: 'flex', flexDirection: 'column', padding: '20px', overflowY: 'auto' }}>
          
          <div style={{ marginBottom: '24px', borderBottom: '1px solid #333', paddingBottom: '16px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '12px' }}>
              <span style={{ 
                fontSize: '12px', 
                fontWeight: 'bold', 
                color: '#000',
                background: '#fff',
                padding: '4px 8px',
                borderRadius: '4px',
                fontFamily: 'var(--font-mono)'
              }}>
                {currentEP.method}
              </span>
              <span style={{ fontSize: '16px', fontWeight: 'bold', color: '#fff', fontFamily: 'var(--font-mono)' }}>
                {currentEP.path}
              </span>
            </div>
            <p style={{ margin: 0, fontSize: '15px', color: '#ccc', lineHeight: '1.6' }}>
              {currentEP.description}
            </p>
            {currentEP.notes && (
              <div style={{ marginTop: '14px', padding: '10px 14px', background: '#111', borderLeft: '2px solid #555', fontSize: '14px', color: '#ddd', lineHeight: '1.5' }}>
                <strong>Note:</strong> {currentEP.notes}
              </div>
            )}
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
            {currentEP.payload && (
              <div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '8px' }}>
                  <Code2 size={14} color="#888" />
                  <span style={{ fontSize: '12px', color: '#fff', fontWeight: 'bold', textTransform: 'uppercase' }}>Request Payload</span>
                </div>
                <div style={{ background: '#000', border: '1px solid #333', borderRadius: '6px', padding: '16px', overflowX: 'auto' }}>
                  <pre style={{ margin: 0, fontSize: '12px', color: '#e5e5e5', fontFamily: 'var(--font-mono)', lineHeight: '1.5' }}>
                    {JSON.stringify(currentEP.payload, null, 2)}
                  </pre>
                </div>
              </div>
            )}

            {currentEP.response && (
              <div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '8px', position: 'relative' }}>
                  <Code2 size={14} color="#888" />
                  <span style={{ fontSize: '12px', color: '#fff', fontWeight: 'bold', textTransform: 'uppercase' }}>Example Response</span>
                  {currentEP.id === 'solve-sync' && (
                    <span style={{ position: 'absolute', right: 0, fontSize: '11px', color: '#888', fontStyle: 'italic' }}>
                      // yet to be added
                    </span>
                  )}
                </div>
                <div style={{ background: '#000', border: '1px solid #333', borderRadius: '6px', padding: '16px', overflowX: 'auto' }}>
                  <pre style={{ margin: 0, fontSize: '12px', color: '#e5e5e5', fontFamily: 'var(--font-mono)', lineHeight: '1.5' }}>
                    {JSON.stringify(currentEP.response, null, 2)}
                  </pre>
                </div>
              </div>
            )}
          </div>

        </div>
      </div>
    </div>
  );
}
